local ffi = require("ffi")

require("lj2zydis.CommonTypes")

ffi.cdef[[
typedef ZydisU32 ZydisStatus;
]]

local ZydisStatusCodes = {
    ZYDIS_STATUS_SUCCESS             = 0x00000000,
    ZYDIS_STATUS_INVALID_PARAMETER = 1,
    ZYDIS_STATUS_INVALID_OPERATION = 2,
    ZYDIS_STATUS_INSUFFICIENT_BUFFER_SIZE = 3,

    -- Decoder
    ZYDIS_STATUS_NO_MORE_DATA = 4,
    ZYDIS_STATUS_DECODING_ERROR = 5,
    ZYDIS_STATUS_INSTRUCTION_TOO_LONG = 6,
    ZYDIS_STATUS_BAD_REGISTER = 7,
    ZYDIS_STATUS_ILLEGAL_LOCK = 8,
    ZYDIS_STATUS_ILLEGAL_LEGACY_PFX = 9,
    ZYDIS_STATUS_ILLEGAL_REX = 10,
    ZYDIS_STATUS_INVALID_MAP = 11,
    ZYDIS_STATUS_MALFORMED_EVEX = 12,
    ZYDIS_STATUS_MALFORMED_MVEX = 13,
    ZYDIS_STATUS_INVALID_MASK = 14,


    -- Formatter
    ZYDIS_STATUS_SKIP_OPERAND = 15,

    -- Encoder
    ZYDIS_STATUS_IMPOSSIBLE_INSTRUCTION = 16,

    -- Misc
    ZYDIS_STATUS_USER = 0x10000000
};
